baseURL = 'https://www.danielmyers.xyz'
languageCode = 'en-us'
title = 'danielmyers-xyz'
theme = "PaperMod"

[[menu.main]]
  identifier = "about"
  name = "About"
 url = "/"
  weight = 1

[[menu.main]]
  identifier = "history"
  name = "History"
  url = "/history/"
  weight = 2

[[menu.main]]
  identifier = "posts"
  name = "Posts"
  url = "/posts/"
  weight = 3

[[menu.main]]
  identifier = "github"
  name = "📁"
  url = "https://github.com/danielmyers-xyz"
  weight = 4


[params]
  description = "GIS engineer specializing in workflow automation, mobile field mapping, and open-source solutions"
  defaultTheme = "auto"
  showReadingTime = true
  hideSummary = false

[params.profileMode]
  enabled = true
  title = "Daniel Myers"
  subtitle = "GIS engineer focused on automation, mobile workflows, and public-sector innovation"
  imageUrl = "/images/profile.jpg"
  imageTitle = "Daniel"
  imageAlt = "Headshot of Daniel"
  buttons = [
    { name = "About", url = "/" },
    { name = "History", url = "/history/" },
    { name = "Posts", url = "/posts/" }
  ]

[params.author]
  name = "Daniel Myers"
  email = "hello@danielmyers.xyz"
  bio = "Personal website for Daniel Myers"

[params.analytics]
  disable = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
