baseURL = 'https://www.danielmyers.xyz'
languageCode = 'en-us'
title = 'danielmyers-xyz'
theme = "congo"

[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "history"
  name = "History"
  url = "/history/"
  weight = 2

[params]
  description = "Personal website of Daniel Myers"
  showReadingTime = true
  hideSummary = false
  enableDarkMode = false

[params.author]
  name = "Daniel Myers"
  email = "hello@danielmyers.xyz"
  bio = "Personal website of Daniel Myers"

[outputs]
  home = ["HTML", "RSS", "JSON"]
