baseURL = 'https://www.danielmyers.xyz'
languageCode = 'en-us'
title = 'danielmyers-xyz'
theme = "PaperMod"

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 1

[[menu.main]]
  identifier = "history"
  name = "History"
  url = "/history/"
  weight = 2

[[menu.main]]
  identifier = "posts"
  name = "Posts"
  url = "/posts/"
  weight = 3

[params]
  description = "Personal website of Daniel Myers"
  defaultTheme = "auto"
  showReadingTime = true
  hideSummary = false

[params.profileMode]
  enabled = true
  title = "Daniel Myers"
  subtitle = "GIS Engineer, speaker, and public tech tinkerer"
  imageUrl = "/images/profile.jpg"
  imageTitle = "Daniel"
  imageAlt = "Headshot of Daniel"
  buttons = [
    { name = "History", url = "/history/" },
    { name = "Posts", url = "/posts/" }
  ]

[params.author]
  name = "Daniel Myers"
  email = "hello@danielmyers.xyz"
  bio = "Personal website of Daniel Myers"

[params.analytics]
  disable = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
